excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://wayde191.github.io
title: iHakula
email: wsun191@gmail.com
author: Wayde Sun
description: My awesome new ihakula site
paginate: 3
google_analytics: 